refractor: change sidecar images repo to registry.k8s.io
openshift/lvm-operator pull request #164
Opened 2022-04-20 16:02 UTC by Madhu-1

Change sidecar images repo to registry.k8s.io which is a redirect to k8s.gcr.io.

Ref: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-04-20 17:31 UTC, nbalacha requested changes
Typo in the commit msg: refractor

2022-04-21 03:18 UTC, Madhu-1 commented
/hold

According to https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/bhoEaoY_AAAJ it is too early to change references permanently. registry.k8s.io is still in a trial phase. keeping it on hold. Once all sidecars migrate to the new repo will revisit this PR.

2022-07-25 05:07 UTC, Madhu-1 commented
All sidecars images are available in new container image repo. This PR is good to go.

cc @nbalacha

2022-07-25 05:07 UTC, Madhu-1 commented
/cancel hold

2022-07-25 05:07 UTC, Madhu-1 commented
/hold cancel

2022-08-18 08:17 UTC, nbalacha commented
/retest

2022-08-18 09:38 UTC, nbalacha commented
/retest

2022-08-25 13:20 UTC, nbalacha commented
/retest

2022-09-27 05:53 UTC, nbalacha commented
@Madhu-1 , please rebase the PR.

2023-04-09 08:01 UTC, closed without merging