Use topolvm upstream
openshift/lvm-operator pull request #226
Opened 2022-07-06 08:55 UTC by sp98

Lvm operator was made to point to the downstream
topolvm branch because some dependent PRs were not
merged upstream. Now that all those PRs are merged
lvm operator can point back to upstream topolvm

Using 0.15.0 topolvm version

2022-07-06 08:57 UTC, sp98 commented on bundle/manifests/lvm-operator.clusterserviceversion.yaml
> -          app.kubernetes.io/name: lvm-operator
`make bundle` removes this label. Need to check again.

2022-07-06 09:03 UTC, Yuggupta27 requested changes

2022-07-21 07:02 UTC, sp98 commented
`make bundle` command removes the `label` from the CSV in operator sdk 1.14 version that I use. Nithya checked on 1.19 and it does not remove the label. 

So, its better to first upgrade the operator sdk version before merging this PR.

2022-09-07 05:48 UTC, sp98 commented on bundle/manifests/lvm-operator.clusterserviceversion.yaml
> -          app.kubernetes.io/name: lvm-operator
This is fixed after operator sdk version upgrade.

2022-09-09 13:01 UTC, riya-singhal31 commented
/test lvm-operator-bundle-e2e-aws

2022-09-12 08:49 UTC, nbalacha commented on Makefile
> +TOPOLVM_CSI_IMAGE ?= quay.io/topolvm/topolvm:0.15.0
This image does not exist upstream which is why the CI is failing.
Lets stick to quay.io/ocs-dev/topolvm:latest

2022-09-12 08:49 UTC, nbalacha commented on go.mod
> -replace github.com/topolvm/topolvm => github.com/red-hat-storage/topolvm v0.11.1-0.20220429122749-ebdea64ffc67
I think this is the only change we really require.

2023-04-09 08:01 UTC, closed without merging