feat: introduce k8s events to lvmcluster and vgmanager
openshift/lvm-operator pull request #403
Opened 2023-08-31 11:03 UTC by jakobmoellerdev

This introduces event recorders to the lvm cluster controller as well as vg manager and issues events on the most important events and failures related to these resources.

2023-08-31 11:04 UTC, jakobmoellerdev commented
/test all

2023-08-31 12:46 UTC, jakobmoellerdev commented
/test all

2023-08-31 14:01 UTC, jakobmoellerdev commented
/test lvm-operator-e2e-aws

2023-08-31 16:17 UTC, jakobmoellerdev commented
/test lvm-operator-e2e-aws-sno

2023-09-01 13:18 UTC, suleymanakbas91 requested changes

2023-09-01 13:49 UTC, jakobmoellerdev commented on pkg/vgmanager/vgmanager_controller.go
> +const EventReasonErrorNoAvailableDevicesForVG EventReasonError = "NoAvailableDevicesForVG"
I think its go convention to write enum strings like that. I can remove it but if you look at other constant enums they should look similar. I agree though they are too long...

2023-09-07 08:05 UTC, suleymanakbas91 commented
/lgtm
/approve

2023-09-07 08:08 UTC, merged