OCPVE-346: chore: move all controllers under `pkg/controllers`
openshift/lvm-operator pull request #434
Opened 2023-09-29 10:56 UTC by jakobmoellerdev

2023-09-29 11:06 UTC, jakobmoellerdev commented
/test all

2023-10-02 17:43 UTC, suleymanakbas91 requested changes

2023-10-02 17:43 UTC, suleymanakbas91 commented on docs/troubleshooting.md
> +This prints information about the disks on the host. Review this information to see why a device is not considered available for LVMS utilization. For example, if a device has partlabel `bios` or `re
Should be inside `internal`. The link does not work now.

2023-10-02 17:43 UTC, suleymanakbas91 commented on internal/cluster/namespace.go
> +// GetOperatorNamespace returns the GetNamespace the operator should be watching for changes
I guess these Namespace -> GetNamespace changes were done unintentionally.

2023-10-02 17:43 UTC, suleymanakbas91 commented on internal/controllers/constants/constants.go
> +	TopolvmControllerContainerName  = TopolvmControllerDeploymentName
We can just delete `TopolvmControllerContainerName` and use `TopolvmControllerDeploymentName` instead.

2023-10-02 17:43 UTC, suleymanakbas91 commented on internal/controllers/lvmcluster/lvmcluster_controller.go
> +	resource2 "github.com/openshift/lvm-operator/internal/controllers/lvmcluster/resource"
why is there a 2 in the end? :)

2023-10-04 08:22 UTC, jakobmoellerdev commented on internal/cluster/namespace.go
> +// GetOperatorNamespace returns the GetNamespace the operator should be watching for changes
yup, good catch... generic refactoring mistake

2023-10-04 08:23 UTC, jakobmoellerdev commented on internal/controllers/lvmcluster/lvmcluster_controller.go
> +	resource2 "github.com/openshift/lvm-operator/internal/controllers/lvmcluster/resource"
i wonder that myself :D

2023-10-04 08:51 UTC, suleymanakbas91 commented
/lgtm
/approve

2023-10-04 10:44 UTC, merged