doc: cleanup design
openshift/lvm-operator pull request #44
Opened 2021-12-23 12:00 UTC by jmolmo

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

2021-12-24 03:06 UTC, leelavg commented on doc/design/cleanup.md
> +- If we decide that a VG need to be deleted, we must delete all the Logical Volumes in it (only one), and also the Physical Volume that supports the VG.
- Operator shouldn't delete logical volumes, that'll be deleted by topolvm itself.
- Pls rephrase if your intention is something else

2021-12-24 03:06 UTC, leelavg commented on doc/design/cleanup.md
> +Two possibilities has been discussed in our [first meeting](https://drive.google.com/file/d/1ltK1XO6Y3gRPVLRLvrmsBJKjXt9s2Klw/view?usp=sharing) about this topic:
- This link will not be accessible to public, we can summarise what we discussed and mention that in this doc

2021-12-27 06:18 UTC, nbalacha commented on doc/design/cleanup.md
> +Remove all the operator resource units and associated resources (config files, socket files).
Does deleting the deployment/daemonset automatically remove these?

2022-01-04 19:17 UTC, travisn requested changes

2022-01-04 19:17 UTC, travisn commented on doc/design/cleanup.md
> +Cleanup: Operations needed to do when the lvm cluster CRD is removed.
This design will be heavily influenced by discussion about the design discussion for whether we have a single LVMCluster CR, or multiple LVMVolumeGroup CRs. This current suggestion assumes the LVMCluster design. With the LVMVolumeGroup design, I see deletion steps to be the following...

When a LVMVolumeGroup is deleted:
1. There is a finalizer on the LVMVolumeGroup that prevents deletion while the cleanup is being processed.
2. The storage class for the LVMVolumeGroup is deleted, so no new PVs can be requested.
3. The operator updates the configuration for each node to signal the removal of the deleted LVMVolumeGroup
4. Each node cleans up:  
   a. If there are any LVs in the VG, block deletion
   b. If there are no LVs in the VG, delete the VG
   c. Depending on the deletion policy on the LVMVolumeGroup (which we can discuss in the future), either wipe the disk(s), or do nothing.

2023-02-07 08:11 UTC, jmolmo commented
/close

2023-02-07 08:11 UTC, closed without merging