OCPVE-353: chore: operf refactoring
openshift/lvm-operator pull request #445
Opened 2023-10-10 10:07 UTC by jakobmoellerdev

performance test refactoring to prepare runnning in CI

2023-10-13 10:32 UTC, suleymanakbas91 requested changes

2023-10-13 10:32 UTC, suleymanakbas91 commented on test/performance/collector.go
> +		c.AVGPerLVMNode.Mem.Quantile99 = c.Total.Mem.Quantile95 / float64(c.nodes)
```suggestion
		c.AVGPerLVMNode.Mem.Quantile99 = c.Total.Mem.Quantile99 / float64(c.nodes)
```

2023-10-13 10:32 UTC, suleymanakbas91 commented on test/performance/collector.go
> +		c.AVGPerLVMNode.Cpu.Quantile99 = c.Total.Cpu.Quantile95 / float64(c.nodes)
```suggestion
		c.AVGPerLVMNode.Cpu.Quantile99 = c.Total.Cpu.Quantile99 / float64(c.nodes)
```

2023-10-13 14:31 UTC, jakobmoellerdev commented
/test lvm-operator-e2e-aws-sno

2023-10-16 07:46 UTC, jakobmoellerdev commented
/retest-required

2023-10-16 07:47 UTC, jakobmoellerdev commented
/hold

testing with https://github.com/openshift/release/pull/44279 on a separate branch to verify perf test execution in CI

2023-10-16 08:01 UTC, merged