OCPEDGE-1230: add metadata size field
openshift/lvm-operator pull request #728
Opened 2024-09-24 10:30 UTC by qJkee

2024-09-24 10:45 UTC, jakobmoellerdev commented on api/v1alpha1/lvmcluster_types.go
> +	ThinPoolMetadataSizeDefault = resource.MustParse("1Gi")
This can be defaulted within the API type I believe

2024-09-24 10:45 UTC, jakobmoellerdev commented on api/v1alpha1/lvmcluster_types.go
> +	MetadataSize *resource.Quantity `json:"metadataSize,omitempty"`
This is missing an explanation on what is used when it is nil as well as minimum and maximum sizes

2024-09-24 10:45 UTC, jakobmoellerdev commented on config/manager/kustomization.yaml
> +  newName: quay.io/bzamalut/lvms
Needs to be removed before merge

2024-09-24 10:45 UTC, jakobmoellerdev commented on internal/controllers/vgmanager/lvm/lvm.go
> +	args = append(args, "--poolmetadatasize", fmt.Sprintf("%vb", metadataSizeBytes))
this is missing a case if the metadataSizeBytes are not provided

2024-09-24 10:45 UTC, jakobmoellerdev commented on internal/controllers/vgmanager/controller.go
> +	metadataSize := lvmv1alpha1.ThinPoolMetadataSizeDefault.Value()
Why do you default to 1Gi here instead of using the Hosts default value from lvm.conf?

2024-10-10 11:09 UTC, suleymanakbas91 requested changes

2024-10-10 11:09 UTC, suleymanakbas91 commented on internal/controllers/vgmanager/controller.go
> +	err = r.LVM.ExtendThinPoolMetadata(ctx, lvName, vgName, newMetadataSize)
I believe this method should only do the validation as it is part of `validateLVs`. The actual extend operation can take place within `extendThinPool` called [here](https://github.com/openshift/lvm-operator/blob/3ca641782ca8ccfd7637d8c385ace913884459e7/internal/controllers/vgmanager/controller.go#L611) or just after it as they are closely related.

2024-10-10 11:09 UTC, suleymanakbas91 commented on api/v1alpha1/lvmcluster_webhook.go
> +	ErrThinPoolMetadataSizeCanBeOnlyIncreased                = errors.New("thin pool metadata size can be only increased")
```suggestion
	ErrThinPoolMetadataSizeCanOnlyBeIncreased                = errors.New("thin pool metadata size can only be increased")
```

2024-10-10 11:09 UTC, suleymanakbas91 commented on api/v1alpha1/lvmcluster_webhook.go
> +			if newThinPoolConfig.MetadataSizeCalculationPolicy == MetadataSizePolicyStatic {
Do we allow switching between Host and Static policies during an update?

2024-10-11 11:44 UTC, suleymanakbas91 commented
/lgtm

2024-10-11 14:11 UTC, merged